import "./api.test.ts";
import "./health.test.ts";
import "./modal-dismiss.test.ts";
import "./order-status.test.ts";
import "./product-filters.test.ts";
import "./product-load.test.ts";
import "./request-diagnostics.test.ts";
import "./telegram-back.test.ts";
import "./transaction-format.test.ts";
